import ModuleShell from '../../components/ModuleShell.jsx'
import ClickReveal from '../../components/ClickReveal.jsx'
import { formatCurrency } from '../../lib/format.js'

const operating = [
  { label: 'Net Income', value: 90000, explanation: 'The starting point — profit from the income statement. The cash flow statement adjusts this because profit isn\'t the same as cash.' },
  { label: 'Depreciation Add-Back', value: 20000, explanation: 'Depreciation reduced profit but no cash actually left the business, so it\'s added back here.' },
  { label: 'Change in Receivables', value: -15000, explanation: 'Customers owe more than before — sales were recorded as revenue, but the cash hasn\'t arrived yet, so it reduces cash.' },
]
const investing = [
  { label: 'Purchase of Equipment', value: -50000, explanation: 'Cash spent buying long-term assets like machinery — an investment in future capacity, not an expense.' },
  { label: 'Sale of Old Vehicle', value: 8000, explanation: 'Cash received from selling an asset the business no longer needs.' },
]
const financing = [
  { label: 'New Bank Loan', value: 40000, explanation: 'Cash raised by borrowing — increases cash now, but creates a future obligation to repay.' },
  { label: 'Dividends Paid', value: -25000, explanation: 'Cash returned to shareholders — reduces cash but reflects a healthy, profitable business.' },
]

const sum = (items) => items.reduce((s, i) => s + i.value, 0)
const netOperating = sum(operating)
const netInvesting = sum(investing)
const netFinancing = sum(financing)
const netChange = netOperating + netInvesting + netFinancing

function Section({ title, subtitle, items, net, tone }) {
  return (
    <div className="mb-5">
      <div className="mb-2">
        <h3 className="text-sm font-bold text-stone-700">{title}</h3>
        <p className="text-xs text-stone-400">{subtitle}</p>
      </div>
      <div className="space-y-1.5">
        {items.map((item) => (
          <ClickReveal
            key={item.label}
            label={item.label}
            value={`${item.value >= 0 ? '+' : '−'} ${formatCurrency(Math.abs(item.value))}`}
            valueClass={item.value >= 0 ? 'text-good' : 'text-bad'}
            explanation={item.explanation}
          />
        ))}
      </div>
      <div className={`mt-1.5 flex items-center justify-between rounded-lg px-4 py-2 ${tone === 'good' ? 'bg-good-soft' : 'bg-stone-50'}`}>
        <span className="text-xs font-semibold text-stone-600">Net Cash from {title}</span>
        <span className={`font-mono text-sm font-bold ${net >= 0 ? 'text-good' : 'text-bad'}`}>
          {net >= 0 ? '+' : '−'} {formatCurrency(Math.abs(net))}
        </span>
      </div>
    </div>
  )
}

export default function CashFlowStatement({ module }) {
  return (
    <ModuleShell
      module={module}
      explainer={
        <>
          <p>
            Profit and cash are not the same thing, and the gap between them is where a lot of businesses actually
            fail. A shop can record a ₹90,000 profit this month and still have less money in the bank than it
            started with — because it sold goods on credit that haven't been paid for yet, or because it just spent
            heavily on new equipment. The income statement tracks what was <em>earned</em>; the cash flow statement
            tracks what actually <em>moved</em>.
          </p>
          <p>
            To make that useful, cash movements are grouped into three buckets depending on where they came from.{' '}
            <strong>Operating</strong> is cash from the core, everyday business; <strong>investing</strong> is cash
            spent on or received from long-term assets like equipment; <strong>financing</strong> is cash from
            lenders and investors, or paid back out to them. Splitting it this way means you can tell whether cash
            grew because the business is genuinely running well, or just because it took out a loan. Click any line
            below to see why it counts as cash in or out.
          </p>
        </>
      }
      whyItMatters="This is the statement that catches problems the income statement can hide — a company can show a profit while its cash from operations is negative, which is an early warning sign lenders watch closely."
    >
      <Section title="Operating Activities" subtitle="Cash generated by day-to-day business operations" items={operating} net={netOperating} />
      <Section title="Investing Activities" subtitle="Cash used for or received from long-term assets" items={investing} net={netInvesting} />
      <Section title="Financing Activities" subtitle="Cash from lenders, investors, or paid out to owners" items={financing} net={netFinancing} />

      <div className="flex items-center justify-between rounded-lg bg-stone-900 px-4 py-2.5 text-white">
        <span className="text-sm font-semibold">Net Change in Cash</span>
        <span className="font-mono text-sm font-bold">
          {netChange >= 0 ? '+' : '−'} {formatCurrency(Math.abs(netChange))}
        </span>
      </div>
    </ModuleShell>
  )
}
